[deps]
Catalyst = "479239e8-5488-4da2-87a7-35f2df7eef83"
DiffEqFlux = "aae7a2af-3d4f-5e19-a356-7da93b79d9d0"
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
HomotopyContinuation = "f213a82b-91d6-5c5d-acf7-10f1c761b327"
Latexify = "23fbe1c1-3f47-55db-b15f-69d7ec21a316"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Setfield = "efcf1570-3423-57d1-acb7-fd33fddbac46"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"

[compat]
Catalyst = "13"
DiffEqFlux = "1.53"
DifferentialEquations = "7.7"
Distributions = "0.25"
Documenter = "0.27"
Flux = "0.13"
HomotopyContinuation = "2.6"
Latexify = "0.15"
ModelingToolkit = "8.47"
Plots = "1.36"
Setfield = "1.1"
SpecialFunctions = "2.1"
Symbolics = "5.0.3"
